---
- name: Install MySQL Server
  yum: pkg={{ item }} state=latest
  with_items:
  - mariadb-server
  - mariadb

- name: Start MySQL Server
  service: name=mariadb state=started enabled=yes

- name: Adds Python MySQL support on RedHat/CentOS
  yum: name=MySQL-python state=present

- name: Sets the root password
  mysql_user: user=root password="{{ mysql_root_password }}" login_user=root login_password="" host=localhost
  ignore_errors: yes

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: login_user="root" login_password="{{ mysql_root_password }}" host=localhost user="" state=absent

- name: Secures the MySQL root user for localhost domain
  mysql_user: login_user="root" login_password="{{ mysql_root_password }}" user=root password="{{ mysql_root_password }}" host="localhost"

- name: Removes the test database
  mysql_db: login_user=root login_password="{{ mysql_root_password }}" db=test state=absent

